/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Dimension;
import javax.swing.JDesktopPane;


/**
 *
 * @author Usuario
 */
public class FrmMenu extends javax.swing.JFrame {

   

    /**
     * Creates new form FrmMenu
     */
    
    public static JDesktopPane jDesktopPane_menu;
    
            
            
    public FrmMenu() {
        initComponents();
        this.setSize(new Dimension(1200, 700));

        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Gestion Vehicular");
        this.setLayout(null);
        jDesktopPane_menu = new JDesktopPane();
        int ancho  = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0,  ancho, (alto - 110));
        this.add(jDesktopPane_menu);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1_nuevo_usuario = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1_gestionar_usuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3_nuevo_vehiculo = new javax.swing.JMenuItem();
        jMenuItem4_gestionar_vehiculo = new javax.swing.JMenuItem();
        jMenuItem5_actualizar_vehiculo = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem6_nuevo_tecnico = new javax.swing.JMenuItem();
        jMenuItem7_gestionar_tecnico = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem8_nueva_categoria = new javax.swing.JMenuItem();
        jMenuItem9_gestionar_categoria = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem10_nuevo_mantenimiento = new javax.swing.JMenuItem();
        jMenuItem11_gestionar_mantenimiento = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem12_detalle_vehiculos = new javax.swing.JMenuItem();
        jMenuItem13_detalle_tecnicos = new javax.swing.JMenuItem();
        jMenuItem14_detalle_categorias = new javax.swing.JMenuItem();
        jMenuItem18_detalle_mantenimientos = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem15_ver_historial = new javax.swing.JMenuItem();
        jMenu_cerrar_sesion = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar5.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar5.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1_nuevo_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMenu1_nuevo_usuario.setText("Usuario");
        jMenu1_nuevo_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu1_nuevo_usuario.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        jMenuItem2.setText("NuevoUsuario");
        jMenuItem2.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1_nuevo_usuario.add(jMenuItem2);

        jMenuItem1_gestionar_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenuItem1_gestionar_usuario.setText("Gestionar Usuarios");
        jMenuItem1_gestionar_usuario.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu1_nuevo_usuario.add(jMenuItem1_gestionar_usuario);

        jMenuBar1.add(jMenu1_nuevo_usuario);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coche1.png"))); // NOI18N
        jMenu2.setText("Vehiculo");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem3_nuevo_vehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        jMenuItem3_nuevo_vehiculo.setText("Nuevo Vehiculo");
        jMenuItem3_nuevo_vehiculo.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu2.add(jMenuItem3_nuevo_vehiculo);

        jMenuItem4_gestionar_vehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenuItem4_gestionar_vehiculo.setText("Gestionar Vehiculo");
        jMenuItem4_gestionar_vehiculo.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu2.add(jMenuItem4_gestionar_vehiculo);

        jMenuItem5_actualizar_vehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenuItem5_actualizar_vehiculo.setText("Actualizar Vehículo");
        jMenuItem5_actualizar_vehiculo.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu2.add(jMenuItem5_actualizar_vehiculo);

        jMenuBar1.add(jMenu2);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenu11.setText("Tecnico");
        jMenu11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu11.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem6_nuevo_tecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        jMenuItem6_nuevo_tecnico.setText("Nuevo Tecnico");
        jMenuItem6_nuevo_tecnico.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu11.add(jMenuItem6_nuevo_tecnico);

        jMenuItem7_gestionar_tecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenuItem7_gestionar_tecnico.setText("Gestionar Tecnico");
        jMenuItem7_gestionar_tecnico.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu11.add(jMenuItem7_gestionar_tecnico);

        jMenuBar1.add(jMenu11);

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenu12.setText("Categoria");
        jMenu12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu12.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem8_nueva_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        jMenuItem8_nueva_categoria.setText("Nueva Categoria");
        jMenuItem8_nueva_categoria.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenuItem8_nueva_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8_nueva_categoriaActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem8_nueva_categoria);

        jMenuItem9_gestionar_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenuItem9_gestionar_categoria.setText("Gestionar Categoria");
        jMenuItem9_gestionar_categoria.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenuItem9_gestionar_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9_gestionar_categoriaActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem9_gestionar_categoria);

        jMenuBar1.add(jMenu12);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenu13.setText("Mantenimiento");
        jMenu13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu13.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem10_nuevo_mantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jMenuItem10_nuevo_mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        jMenuItem10_nuevo_mantenimiento.setText("Nuevo Mantenimiento");
        jMenuItem10_nuevo_mantenimiento.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu13.add(jMenuItem10_nuevo_mantenimiento);

        jMenuItem11_gestionar_mantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jMenuItem11_gestionar_mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenuItem11_gestionar_mantenimiento.setText("Gestionar Mantenimiento");
        jMenuItem11_gestionar_mantenimiento.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu13.add(jMenuItem11_gestionar_mantenimiento);

        jMenuBar1.add(jMenu13);

        jMenu14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes.png"))); // NOI18N
        jMenu14.setText("Detalle");
        jMenu14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu14.setPreferredSize(new java.awt.Dimension(150, 30));

        jMenuItem12_detalle_vehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coche1.png"))); // NOI18N
        jMenuItem12_detalle_vehiculos.setText("Detalle Vehiculos");
        jMenuItem12_detalle_vehiculos.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu14.add(jMenuItem12_detalle_vehiculos);

        jMenuItem13_detalle_tecnicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenuItem13_detalle_tecnicos.setText("Detalle Tecnicos");
        jMenuItem13_detalle_tecnicos.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu14.add(jMenuItem13_detalle_tecnicos);

        jMenuItem14_detalle_categorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenuItem14_detalle_categorias.setText("Detalle Categorias");
        jMenuItem14_detalle_categorias.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu14.add(jMenuItem14_detalle_categorias);

        jMenuItem18_detalle_mantenimientos.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jMenuItem18_detalle_mantenimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenuItem18_detalle_mantenimientos.setText("Detalle Mantenimientos");
        jMenuItem18_detalle_mantenimientos.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenuItem18_detalle_mantenimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18_detalle_mantenimientosActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem18_detalle_mantenimientos);

        jMenuBar1.add(jMenu14);

        jMenu15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        jMenu15.setText("Historial");
        jMenu15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu15.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem15_ver_historial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        jMenuItem15_ver_historial.setText("Ver Historial");
        jMenuItem15_ver_historial.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu15.add(jMenuItem15_ver_historial);

        jMenuBar1.add(jMenu15);

        jMenu_cerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu_cerrar_sesion.setText("Cerrar Sesion");
        jMenu_cerrar_sesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu_cerrar_sesion.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenuItem17.setText("Cerrar Sesion");
        jMenuItem17.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu_cerrar_sesion.add(jMenuItem17);

        jMenuBar1.add(jMenu_cerrar_sesion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem18_detalle_mantenimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18_detalle_mantenimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18_detalle_mantenimientosActionPerformed

    private void jMenuItem8_nueva_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8_nueva_categoriaActionPerformed
        // TODO add your handling code here:
        InterCategoria interCategoria = new InterCategoria();
        jDesktopPane_menu.add(interCategoria);
        interCategoria.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem8_nueva_categoriaActionPerformed

    private void jMenuItem9_gestionar_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9_gestionar_categoriaActionPerformed
        // TODO add your handling code here:
        InterGestionarCategoria interGestionarCategoria = new InterGestionarCategoria();
        jDesktopPane_menu.add(interGestionarCategoria);
        interGestionarCategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem9_gestionar_categoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu1_nuevo_usuario;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem10_nuevo_mantenimiento;
    private javax.swing.JMenuItem jMenuItem11_gestionar_mantenimiento;
    private javax.swing.JMenuItem jMenuItem12_detalle_vehiculos;
    private javax.swing.JMenuItem jMenuItem13_detalle_tecnicos;
    private javax.swing.JMenuItem jMenuItem14_detalle_categorias;
    private javax.swing.JMenuItem jMenuItem15_ver_historial;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18_detalle_mantenimientos;
    private javax.swing.JMenuItem jMenuItem1_gestionar_usuario;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3_nuevo_vehiculo;
    private javax.swing.JMenuItem jMenuItem4_gestionar_vehiculo;
    private javax.swing.JMenuItem jMenuItem5_actualizar_vehiculo;
    private javax.swing.JMenuItem jMenuItem6_nuevo_tecnico;
    private javax.swing.JMenuItem jMenuItem7_gestionar_tecnico;
    private javax.swing.JMenuItem jMenuItem8_nueva_categoria;
    private javax.swing.JMenuItem jMenuItem9_gestionar_categoria;
    private javax.swing.JMenu jMenu_cerrar_sesion;
    // End of variables declaration//GEN-END:variables
}
